apiVersion: v1
kind: Service
metadata:
  name: static-page-wilson-liao
spec:
  type: ClusterIP
  selector:
    component: web
    student: wilson-liao
  ports:
    - port: 3000
      name: http
      targetPort: 3000