apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-page-wilson-liao
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      component: web
      student: wilson-liao
  template:
    metadata:
      labels:
        component: web
        student: wilson-liao
    spec:
      containers:
        - name: static
          image: wilsonliao/wisepaas-static:1.0.1
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 20m
              memory: 32Mi
              ephemeral-storage: 32Mi
            requests:
              cpu: 10m
              memory: 32Mi